archives:
- id: archive
  name_template: '{{ .Binary }}-v{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
  - make build_sdks
builds:
- binary: pulumi-resource-ec
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -X github.com/springload/pulumi-tf-provider-ec/provider/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-ec/
changelog:
  skip: true
release:
  disable: false
  extra_files:
    - glob: sdk/python/bin/dist/pulumi_ec-*.tar.gz
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
