# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'apikey',
    'endpoint',
    'insecure',
    'password',
    'timeout',
    'username',
    'verbose',
    'verbose_credentials',
    'verbose_file',
]

__config__ = pulumi.Config('ec')

apikey = __config__.get('apikey')
"""
API Key to use for API authentication. The only valid authentication mechanism for the Elasticsearch Service.
"""

endpoint = __config__.get('endpoint')
"""
Endpoint where the terraform provider will point to. Defaults to "https://api.elastic-cloud.com".
"""

insecure = __config__.get('insecure')
"""
Allow the provider to skip TLS validation on its outgoing HTTP calls.
"""

password = __config__.get('password')
"""
Password to use for API authentication. Available only when targeting ECE Installations or Elasticsearch Service
Private.
"""

timeout = __config__.get('timeout')
"""
Timeout used for individual HTTP calls. Defaults to "1m".
"""

username = __config__.get('username')
"""
Username to use for API authentication. Available only when targeting ECE Installations or Elasticsearch Service
Private.
"""

verbose = __config__.get('verbose')
"""
When set, a "request.log" file will be written with all outgoing HTTP requests. Defaults to "false".
"""

verbose_credentials = __config__.get('verboseCredentials')
"""
When set with verbose, the contents of the Authorization header will not be redacted. Defaults to "false".
"""

verbose_file = __config__.get('verboseFile')
"""
Timeout used for individual HTTP calls. Defaults to "1m".
"""

