// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Ec
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("ec");
        /// <summary>
        /// API Key to use for API authentication. The only valid authentication mechanism for the Elasticsearch Service.
        /// </summary>
        public static string? Apikey { get; set; } = __config.Get("apikey");

        /// <summary>
        /// Endpoint where the terraform provider will point to. Defaults to "https://api.elastic-cloud.com".
        /// </summary>
        public static string? Endpoint { get; set; } = __config.Get("endpoint");

        /// <summary>
        /// Allow the provider to skip TLS validation on its outgoing HTTP calls.
        /// </summary>
        public static bool? Insecure { get; set; } = __config.GetBoolean("insecure");

        /// <summary>
        /// Password to use for API authentication. Available only when targeting ECE Installations or Elasticsearch Service
        /// Private.
        /// </summary>
        public static string? Password { get; set; } = __config.Get("password");

        /// <summary>
        /// Timeout used for individual HTTP calls. Defaults to "1m".
        /// </summary>
        public static string? Timeout { get; set; } = __config.Get("timeout");

        /// <summary>
        /// Username to use for API authentication. Available only when targeting ECE Installations or Elasticsearch Service
        /// Private.
        /// </summary>
        public static string? Username { get; set; } = __config.Get("username");

        /// <summary>
        /// When set, a "request.log" file will be written with all outgoing HTTP requests. Defaults to "false".
        /// </summary>
        public static bool? Verbose { get; set; } = __config.GetBoolean("verbose");

        /// <summary>
        /// When set with verbose, the contents of the Authorization header will not be redacted. Defaults to "false".
        /// </summary>
        public static bool? VerboseCredentials { get; set; } = __config.GetBoolean("verboseCredentials");

        /// <summary>
        /// Timeout used for individual HTTP calls. Defaults to "1m".
        /// </summary>
        public static string? VerboseFile { get; set; } = __config.Get("verboseFile");

    }
}
