// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ec

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetECStack(ctx *pulumi.Context, args *GetECStackArgs, opts ...pulumi.InvokeOption) (*GetECStackResult, error) {
	var rv GetECStackResult
	err := ctx.Invoke("ec:index/getECStack:getECStack", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getECStack.
type GetECStackArgs struct {
	Lock         *bool  `pulumi:"lock"`
	Region       string `pulumi:"region"`
	VersionRegex string `pulumi:"versionRegex"`
}

// A collection of values returned by getECStack.
type GetECStackResult struct {
	Accessible         bool                         `pulumi:"accessible"`
	Allowlisted        bool                         `pulumi:"allowlisted"`
	Apms               []GetECStackApm              `pulumi:"apms"`
	Elasticsearches    []GetECStackElasticsearch    `pulumi:"elasticsearches"`
	EnterpriseSearches []GetECStackEnterpriseSearch `pulumi:"enterpriseSearches"`
	// The provider-assigned unique ID for this managed resource.
	Id                string             `pulumi:"id"`
	Kibanas           []GetECStackKibana `pulumi:"kibanas"`
	Lock              *bool              `pulumi:"lock"`
	MinUpgradableFrom string             `pulumi:"minUpgradableFrom"`
	Region            string             `pulumi:"region"`
	UpgradableTos     []string           `pulumi:"upgradableTos"`
	Version           string             `pulumi:"version"`
	VersionRegex      string             `pulumi:"versionRegex"`
}
