// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ec

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupECDeployment(ctx *pulumi.Context, args *LookupECDeploymentArgs, opts ...pulumi.InvokeOption) (*LookupECDeploymentResult, error) {
	var rv LookupECDeploymentResult
	err := ctx.Invoke("ec:index/getECDeployment:getECDeployment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getECDeployment.
type LookupECDeploymentArgs struct {
	Id string `pulumi:"id"`
}

// A collection of values returned by getECDeployment.
type LookupECDeploymentResult struct {
	Apms                 []GetECDeploymentApm              `pulumi:"apms"`
	DeploymentTemplateId string                            `pulumi:"deploymentTemplateId"`
	Elasticsearches      []GetECDeploymentElasticsearch    `pulumi:"elasticsearches"`
	EnterpriseSearches   []GetECDeploymentEnterpriseSearch `pulumi:"enterpriseSearches"`
	Healthy              bool                              `pulumi:"healthy"`
	Id                   string                            `pulumi:"id"`
	Kibanas              []GetECDeploymentKibana           `pulumi:"kibanas"`
	Name                 string                            `pulumi:"name"`
	Observabilities      []GetECDeploymentObservability    `pulumi:"observabilities"`
	Region               string                            `pulumi:"region"`
	Tags                 map[string]string                 `pulumi:"tags"`
	TrafficFilters       []string                          `pulumi:"trafficFilters"`
}
