// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ec

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "ec:index/eCDeployment:ECDeployment":
		r = &ECDeployment{}
	case "ec:index/eCDeploymentExtension:ECDeploymentExtension":
		r = &ECDeploymentExtension{}
	case "ec:index/eCDeploymentTrafficFilter:ECDeploymentTrafficFilter":
		r = &ECDeploymentTrafficFilter{}
	case "ec:index/eCDeploymentTrafficFilterAssociation:ECDeploymentTrafficFilterAssociation":
		r = &ECDeploymentTrafficFilterAssociation{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:ec" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"ec",
		"index/eCDeployment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"ec",
		"index/eCDeploymentExtension",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"ec",
		"index/eCDeploymentTrafficFilter",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"ec",
		"index/eCDeploymentTrafficFilterAssociation",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"ec",
		&pkg{version},
	)
}
