// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("ec");

/**
 * API Key to use for API authentication. The only valid authentication mechanism for the Elasticsearch Service.
 */
export let apikey: string | undefined = __config.get("apikey");
/**
 * Endpoint where the terraform provider will point to. Defaults to "https://api.elastic-cloud.com".
 */
export let endpoint: string | undefined = __config.get("endpoint");
/**
 * Allow the provider to skip TLS validation on its outgoing HTTP calls.
 */
export let insecure: boolean | undefined = __config.getObject<boolean>("insecure");
/**
 * Password to use for API authentication. Available only when targeting ECE Installations or Elasticsearch Service
 * Private.
 */
export let password: string | undefined = __config.get("password");
/**
 * Timeout used for individual HTTP calls. Defaults to "1m".
 */
export let timeout: string | undefined = __config.get("timeout");
/**
 * Username to use for API authentication. Available only when targeting ECE Installations or Elasticsearch Service
 * Private.
 */
export let username: string | undefined = __config.get("username");
/**
 * When set, a "request.log" file will be written with all outgoing HTTP requests. Defaults to "false".
 */
export let verbose: boolean | undefined = __config.getObject<boolean>("verbose");
/**
 * When set with verbose, the contents of the Authorization header will not be redacted. Defaults to "false".
 */
export let verboseCredentials: boolean | undefined = __config.getObject<boolean>("verboseCredentials");
/**
 * Timeout used for individual HTTP calls. Defaults to "1m".
 */
export let verboseFile: string | undefined = __config.get("verboseFile");
