// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getECDeployment(args: GetECDeploymentArgs, opts?: pulumi.InvokeOptions): Promise<GetECDeploymentResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ec:index/getECDeployment:getECDeployment", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getECDeployment.
 */
export interface GetECDeploymentArgs {
    readonly id: string;
}

/**
 * A collection of values returned by getECDeployment.
 */
export interface GetECDeploymentResult {
    readonly apms: outputs.GetECDeploymentApm[];
    readonly deploymentTemplateId: string;
    readonly elasticsearches: outputs.GetECDeploymentElasticsearch[];
    readonly enterpriseSearches: outputs.GetECDeploymentEnterpriseSearch[];
    readonly healthy: boolean;
    readonly id: string;
    readonly kibanas: outputs.GetECDeploymentKibana[];
    readonly name: string;
    readonly observabilities: outputs.GetECDeploymentObservability[];
    readonly region: string;
    readonly tags: {[key: string]: string};
    readonly trafficFilters: string[];
}
